module.exports.descriptors = [
    'Floresta',
    'Camping',
    'Pedra',
    'Nascente',
    'Cascata',
    'Antílopes',
    'Silêncio',
    'Madeira',
    'Recanto',
    'Selva',
    'Lagoa',
    'Lago',
    'Neblina',
    'Mar',
    'Mato',
    'Cabanas',
    'Nevoeiro',
    'Savana',
    'Matinho',
    'Moita',
    'Campos',
    'Pampas',
    'Cantinho',
    'Sabor'
]

module.exports.places = [
    'do Veado',
    'do Antílope',
    'da Jaguatirica',
    'da Onça',
    'Selvagem',
    'Gaúcho',
    'Carioca',
    'dos Veadinhos',
    'da Glória',
    'do Lula',
    'de Açúcar',
    'de Sal',
    'Mole',
    'do Tigre',
    'dos Veados',
    'da Dona Antílope',
    'Antifascista',
    'do Arco-Íris',
    'Verde',
    'Azul',
    'da Netureza',
    'da Matilde'
]

